### PR TITLE
fix RPC Failed with a Port backend 

### LINKED ISSUE #91: Is it possible to use the IndexedDB backend in a worker ?
In my main thread, I can configure zenfs to access a remote filesystem running in a webworker in a different context. 

When using the InMemory backend, everything works as expected.
```typescript
// worker.ts
import { attachFS, resolveMountConfig, InMemory } from '@zenfs/core';

const myFS = await resolveMountConfig({ backend: InMemory, name: 'foo' });
attachFS(self, myFS);
```

```typescript
// main.ts
import { configure, Port, fs } from '@zenfs/core';
const worker = new Worker(new URL('./worker.ts', import.meta.url), {
      type: 'module',
    });

await configure({
  mounts: {
    '/port': {
      backend: Port,
      port: worker,
    },
  },
});

// Can now use methods on fs to interact with filesystem running in web worker thread..
```

But if I try to use the IndexedDB backend in the worker, i get an error.

```typescript
// worker.ts
import { attachFS, resolveMountConfig } from '@zenfs/core';
import {IndexedDB} from "@zenfs/dom";

const myFS = await resolveMountConfig({ backend: IndexedDB, name: 'foo' });
attachFS(self, myFS);
```

The error is `Error: RPC Failed`,this line: 
https://github.com/zen-fs/core/blob/a6287a9bed0aea12b6259084d99efeccd9577459/src/backends/port/rpc.ts#L89

I have a feeling that I am not using the Port backend as its intended, apologies in advance if that is the case!

### PR DESCRIPTION
**Pull request by UnCor3**
I have been able to fix the issue with these changes (Fixes #91)

### CODE REVIEW

**Review by james-pre — CHANGES_REQUESTED** [review]
Thanks for the PR!

I have a few concerns regarding the implementation:

Please explain how the "signal boot" works. One concern I have is that the "remote" thread will call `attachFS` *before* the "main" thread calls `configure`. This creates a race condition, which is a bug I'd like to avoid. Also, is this something that could be fixed by changing `FileSystem.ready()`'s behavior with `Port`?

This is one case where the code now depends on a platform. This is something I'd like to avoid. This library should work the same regardless of the platform used. This means if one platform does a handshake or something to initialize `Port`, so should all of the others. We should try to be as consistent as possible.

The code doesn't follow the guidelines I've been using. This is definitely my fault for not updating [contributing.md](https://github.com/zen-fs/core/blob/main/contributing.md) as the guidelines changed. It's updated now, so you can review the section on code when you have a chance. This should clear things up.

I'd like to see more types and documentation. This code can be difficult to read, partially because of the lack of types and documentation. While I have a *very* good knowledge of the codebase and didn't struggle to understand what is being done, a new contributor might be completely lost.

Please make sure anything you add or change has tests. #66 Really shows how much we need more tests.

Thanks again for opening the PR. I hope my feedback is helpful, I try to be thorough in my reviews.

**Comment by UnCor3** [comment]
Hey, first of all thank you for taking the time and reviewing this pr


I realized that when I wrap main thread setup in a setTimeout like so everything works fine 


```ts
import { configure, Port, fs } from "@zenfs/core";
import FooWorker from "./foo.worker?worker";
export class GitWorkerIPC {
  constructor() {
    this.init();
  }
  private async init() {
    setTimeout(async () => {
      try {
        await configure({
          mounts: {
            "/port": {
              backend: Port,
              port: new FooWorker(),
            },
          },
        });
          console.log({ result: fs.readdirSync("/") });
      } catch (error) {
          console.error(error);
      }
    }, 1000);
  }
}

```


> One concern I have is that the "remote" thread will call attachFS before the "main" thread calls configure. This creates a race condition,

There already is a race condition because in order to attachFs, you need to await resolveMountConfig or configureSingle etc on worker thread. This is why the code above works with a worker  setup like this


```ts
import { attachFS, resolveMountConfig, fs } from "@zenfs/core";
import { IndexedDB } from "@zenfs/dom";

//it works without an async function declaration but vite wants me to use esnext as target
async function init() {
  try {
    const myFS = await resolveMountConfig({ backend: IndexedDB });
    attachFS(self, myFS);
    myFS.mkdirSync("/mnt", 1, {});
  } catch (error) {
    console.error(error);
  }
}
init();

```


Once i realized this i said to myself why not await a promise that is resolved by a ready indication from worker (boot signal) then do the required things because otherwise,with a bit of uncertainty, I think we need to implement resolveMountConfigSync or  configureSingleSync  



> This is one case where the code now depends on a platform. This is something I'd like to avoid. This library should work the same regardless of the platform used..

You are absolutely right on this one but i have not changed any core functionality just added an additional step for Web Workers also this pr could be used as a hotfix 


> is this something that could be fixed by changing FileSystem.ready() ?..

When i checked the FileSystem.ready seems to be an empty function that is just async I did not get what i could implement there


> Please make sure anything you add or change has tests. https://github.com/zen-fs/core/issues/66 Really shows how much we need more tests.

Since i made a fix for Web Workers i can add a test for Web Workers , i will update tests accordingly as well



### If you thing you have a better approach as to fix this issue I'd be more than happy to update my code accordingly

**Comment by UnCor3** [comment]
@james-pre check [this](https://stackblitz.com/edit/vitejs-vite-qtfkhk) reproduction with setTimeout it works

**Comment by james-pre** [comment]
> I realized that when I wrap main thread setup in a setTimeout like so everything works fine

We need to figure out *why*, and then fix the underlying issue. This is unfortunately very difficult.

> There already is a race condition because in order to `attachFS`, you need to await `resolveMountConfig` or `configureSingle` etc on worker thread. This is why the code above works with a worker setup like this

Not necessarily. `await` makes it so the worker will not parse incoming requests until the underlying FS is ready. If we can do this in a way that catches any messages sent before `attachFS`, and replays them afterward, I think the issue will be fixed. I think a new function could do that nicely, maybe something like `RPC.catchMessages`. We can wrap the new function, `attachFS`, and the configuration all into another function (`configureRemote`?) to make users' lives easier.

> > This is one case where the code now depends on a platform. This is something I'd like to avoid. This library should work the same regardless of the platform used.
> 
> You are absolutely right on this one but i have not changed any core functionality just added an additional step for Web Workers also this pr could be used as a hotfix

Still, this means that behavior is inconsistent between browsers and Node, which is a problem.

> When i checked the FileSystem.ready seems to be an empty function that is just async I did not get what i could implement there

`FileSystem.ready` is empty, but many subclasses use it for initialization logic.

> Since i made a fix for Web Workers i can add a test for Web Workers , i will update tests accordingly as well

Thanks!

​  
​  
To sum up the potential solutions I mentioned earlier with code:

backends/port/rpc.ts
```ts
export function catchMessages(port: Port): () => void {
	const events: _MessageEvent[];
	const handler = events.push.bind(events);

	attach(port, handler);

	return function () {
		// Now I'm not sure if `detach` works correctly because of function identity equality
		detach(port, handler);
		for (const event of events) {
			const data = 'data' in event ? event.data : event;
			if (isMessage(data)) {
				// emit/dispatch the event. Note we need to check for the right method to trigger handlers.
				port.emit('message', data);
			}
		}
	};
}
```

backends/port/fs.ts
```ts
async function configureRemoteMount<T extends MountConfiguration>(port: RPC.Port, config: T): Promise<void> {
	const stopAndReplay = RPC.catchMessages(port);
	const fs = await resolveMountConfig(config);
	attachFS(port, fs);
	stopAndReplay();
}
```

*Please note*: This is rough code I came up with quickly, it probably needs a lot of review and maybe some bug fixing.

**Pull request closed without merging**
